### PR TITLE
Version-2 of webapp

### PR DESCRIPTION
**Pull request by armintalaie**
rebuilt with svelte; taken and expanded on past designs

not connected to any servers as of now. good to merge and spread the fe work

some screenshots:
Screenshot 2023-05-12 at 9 18 52 PM

Screenshot 2023-05-12 at 9 19 00 PM

Screenshot 2023-05-12 at 9 19 07 PM

Screenshot 2023-05-12 at 9 19 15 PM

### CODE REVIEW

**Comment by Michaeltaoma** [comment]
I ran into some error when trying to build/start dev server, is this expected?

```
TypeError: [postcss] Cannot read properties of undefined (reading 'config')
```
I guess I am missing some config file, what should the file be?

**Comment by armintalaie** [comment]
> I ran into some error when trying to build/start dev server, is this expected?
> 
> ```
> TypeError: [postcss] Cannot read properties of undefined (reading 'config')
> ```
> 
> I guess I am missing some config file, what should the file be?

in the `app` directory?

**Comment by Michaeltaoma** [comment]
> > I ran into some error when trying to build/start dev server, is this expected?
> > ```
> > TypeError: [postcss] Cannot read properties of undefined (reading 'config')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess I am missing some config file, what should the file be?
> 
> in the `app` directory?

Yes, in the `app` directory.

**Comment by Michaeltaoma** [comment]
> > I ran into some error when trying to build/start dev server, is this expected?
> > ```
> > TypeError: [postcss] Cannot read properties of undefined (reading 'config')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess I am missing some config file, what should the file be?
> 
> in the `app` directory?

I had to add a `tailwind.config.js` file in the `app/` to run it.

```
module.exports = {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
}
```
But the frontend looks good!

**Comment by Michaeltaoma** [comment]
> > > I ran into some error when trying to build/start dev server, is this expected?
> > > ```
> > > TypeError: [postcss] Cannot read properties of undefined (reading 'config')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I guess I am missing some config file, what should the file be?
> > 
> > 
> > in the `app` directory?
> 
> I had to add a `tailwind.config.js` file in the `app/` to run it.
> 
> ```
> module.exports = {
>   content: [],
>   theme: {
>     extend: {},
>   },
>   plugins: [],
> }
> ```
> 
> But the frontend looks good!

@armintalaie You wanna include that to your commit?

**Pull request closed without merging**
