### PR TITLE
Convert CSS to SCSS

### PR DESCRIPTION
**Pull request by ryanmckim**
- Separated App.css into SCSS files for different components.
- Wrapped the extension around a div to implement SCSS nesting.
- Renamed identifiers in styles.css to resolve browser CSS clashing.

### CODE REVIEW

**Comment by Michaeltaoma** [comment]
Looks like some layout have been changed.

Snipaste_2022-12-01_09-35-56

**Comment by ryanmckim** [comment]
> Looks like some layout have been changed.
> 
> Snipaste_2022-12-01_09-35-56

I'll get to fixing it right away.

**Comment by armintalaie** [comment]
I think you might have accidentally ran some npm scripts from the top level. Basically the top level should only have the fe, be and summary folder and you should delete the node_modules and whatever else.

**Comment by ryanmckim** [comment]
> I think you might have accidentally ran some npm scripts from the top level. Basically the top level should only have the fe, be and summary folder and you should delete the node_modules and whatever else.

For sure.  I'll delete it and the CSS is still overriding some pages, so I will update when that gets fixed as well.

**Comment by armintalaie** [comment]
> > I think you might have accidentally ran some npm scripts from the top level. Basically the top level should only have the fe, be and summary folder and you should delete the node_modules and whatever else.
> 
> 
> 
> For sure.  I'll delete it and the CSS is still overriding some pages, so I will update when that gets fixed as well.

Sounds good!

**Comment by Michaeltaoma** [comment]
Hi, Lens layout has been changed.

Now:

Snipaste_2022-12-07_10-28-48

before:

Snipaste_2022-12-07_10-30-34

**Review by Michaeltaoma — APPROVED** [review]
looks good to me!

**Pull request merged**
