### PR TITLE
Added simple extractive summarizer

### PR DESCRIPTION
**Pull request by ymnglli**

### CODE REVIEW

**Comment by armintalaie** [comment]
after @sauravbanna merges his [PR](https://github.com/ubclaunchpad/Essentially/pull/40), we will merge this.

in the meantime, please add the flask API for the summary so the node backend can call. reach out to @sauravbanna if unclear how the main server will use this api

**Comment by armintalaie** [comment]
@ymnglli
please remove the placeholder file. also when please remove the cell output of Jupiter notebooks and push them again (the outputs don't need to be committed)
after these, do a last check with @Hgjnnf and have him review and merge it. thanks!



_the comments also have a different convention. (for later we should update at)._

**Review by armintalaie — APPROVED** [review]

**Comment by ymnglli** [comment]
Sounds good! btw are you sure you want to remove the outputs for dynamic_chunking.ipynb? We won't be able to see the results of the clustering or the graphs.

**Comment by armintalaie** [comment]
honestly i'm not sure if u think they should be there then that's fine

**Review by Hgjnnf — APPROVED** [review]
LGTM! I think in the future, we can put the comments in summarization.py in our wiki.

**Pull request merged**
